# Generated by Django 3.2.2 on 2021-05-12 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_alter_movie_writer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='totalSeasons',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
